server:
  port: 8081
spring:
  cloud:
    gateway:
      default-filters:
        - name: LogFilter
      routes:
        - id: catalogRoute
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**